	.align 2
voicegroup287:: @ 
	voice_keysplit_all voicegroup001 @ Drums / Acoustic Grand
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Bright Acoustic
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Electric Grand
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Honky-Tonk
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Electric Piano 1
	voice_keysplit voicegroup005, KeySplitTable1 @ Electric Piano 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Harpsichord
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Clav
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Celesta
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 72, 249 @ Glockenspiel
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Music Box
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Vibraphone
	voice_keysplit voicegroup239, KeySplitTable1 @ Marimba
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204 @ Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 216, 90, 242 @ Tubular Bells
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Dulcimer
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Draawnar Organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 210 @ Percussive Organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Rock Organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Church Organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Reed Organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165 @ Accordion
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Harmonica
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Tango Accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 76 @ Acoustic Guitar(nylon)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Acoustic Guitar(Steel)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Electric Guitar(jazz)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Electric Guitar(clean)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Electric Guitar(Muted)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Overdriven Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Distortion guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Guitar Harmonics
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Acoustic Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Electric bass(finger)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Electric bass(pick)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Fretless bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Slap Bass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Slap Bass 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Synth Bass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Synth Bass 2
	voice_keysplit voicegroup213, KeySplitTable24 @ Violin
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Viola
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Cello
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Contrabass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Tremolo Strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pizzicato Strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Orchestral Strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 0, 180, 246 @ Timpani
	voice_keysplit voicegroup006, KeySplitTable2     @ String Ensemble 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ String Ensemble 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ SynthStrings 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ SynthStrings 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Choir Aahs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Voice Oohs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Synth Voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Orchestra hit
	voice_keysplit voicegroup007, KeySplitTable3 @ Trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Trombone
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Tuba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Muted Trumpet
	voice_keysplit voicegroup009, KeySplitTable5 @ French Horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Brass Section
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Synth Brass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Synth Brass 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Soprano Sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Alto Sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Tenor Sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Baritone Sax
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 43, 165, 103, 165 @ Oboe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ English Horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Bassoon
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Piccolo
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165    @ flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Recorder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pan Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Blown Bottle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Skakuhachi
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Whistle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Ocarina
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Lead 1 (square)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Lead 2 (sawtooth)
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 7, 0 @ Lead 3 (calliope)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Lead 4 (chiff)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Lead 5 (charang)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Lead 6 (voice)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Lead 7 (fifths)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Lead 8 (bass+lead)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pad 1 (new age)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 210 @ Pad 2 (warm)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pad 2 (warm)
	voice_directsound 60, 0, DirectSoundWaveData_hg_choirc5, 255, 197, 255, 171 @ Pad 3 (polysynth)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pad 4 (choir)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pad 5 (bowed)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pad 6 (metallic)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pad 7 (halo)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Pad 8 (sweep)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 1 (rain)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 2 (soundtrack)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 3 (crystal)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 4 (atmosphere)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 5 (brightness)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 6 (goblins)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 7 (echoes)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ FX 8 (sci-fi)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Sitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Banjo
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Shamisen
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Koto
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Kalimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Bagpipe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Fiddle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Shanai
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Tinklebell
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Agogo
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Steel Drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Woodblock
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Taiko Drum
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Synth Drum
	voice_directsound 61, 102, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216 @ Reverse Cymbal
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Guitar Fret Noise
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Breath Noise
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 255, 165, 103, 235 @ Acoustic Grand (right) @ Seashore
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Bird Tweet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Telephone Ring
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ Helicopter
	voice_noise_alt 60, 0, 0, 0, 1, 7, 1 @ Applause
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ Gunshot
